import { DataItem } from "../types";

export const dataItems: DataItem [] = [
    {
      id: 1,
      name: 'Data 1',
      description: 'End-to-end testing suite for the main e-commerce platform',
      lastUpdated: '2h ago',
      global: true,
    },
    {
      id: 2,
      name: 'Data 2',
      description: 'Automated testing framework for iOS and Android applications',
      lastUpdated: '5h ago',
      global: false,
    },
    {
      id: 3,
      name: 'Data 3',
      description: 'Comprehensive API testing suite for microservices',
      lastUpdated: '1d ago',
      global: true,
    },
    {
      id: 4,
      name: 'Data 4',
      description: 'Security and performance testing for payment systems',
      lastUpdated: '3d ago',
      global: false,
    },
    {
      id: 5,
      name: 'Data 5',
      description: 'Security and performance testing for payment systems',
      lastUpdated: '3d ago',
      global: false,
    },
    {
      id: 6,
      name: 'Data 6',
      description: 'Security and performance testing for payment systems',
      lastUpdated: '3d ago',
      global: false,
    },
    {
      id: 7,
      name: 'Data 7',
      description: 'Security and performance testing for payment systems',
      lastUpdated: '3d ago',
      global: false,
    },
    {
      id: 8,
      name: 'Data 8',
      description: 'Security and performance testing for payment systems',
      lastUpdated: '3d ago',
      global: false,
    },
    {
      id: 9,
      name: 'Data 9',
      description: 'Security and performance testing for payment systems',
      lastUpdated: '3d ago',
      global: false,
    },
    {
      id: 10,
      name: 'Data 10',
      description: 'Security and performance testing for payment systems',
      lastUpdated: '3d ago',
      global: false,
    },
    {
      id: 11,
      name: 'Data 11',
      description: 'Security and performance testing for payment systems',
      lastUpdated: '3d ago',
      global: false,
    },
    {
      id: 12,
      name: 'Data 12',
      description: 'Security and performance testing for payment systems',
      lastUpdated: '3d ago',
      global: false,
    },
    {
      id: 13,
      name: 'Data 13',
      description: 'Security and performance testing for payment systems',
      lastUpdated: '3d ago',
      global: false,
    },
  ];